version: '3.8'

services:
  incident-api:
    image: urielre46/monomap_api:latest
    container_name: monomap_api
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: ${MONGO_URL_DOCKER}
      PORT: ${PORT}

    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_volume:/data/db

volumes:
  mongodb_volume: